name: Update Lean
on:
  schedule:
    - cron: "0 11 * * 4"
  workflow_dispatch:
  
jobs:
  update_lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Lean project
        uses: Seasawher/lean-update@main # 自前のアクションを使用する
        with:
          update_if_modified: lean-toolchain
