name: Update Lean
on:
  schedule:
    - cron: "0 11 * * 4"
  workflow_dispatch:
  
jobs:
  update_lean:
    runs-on: ubuntu-latest
    permissions:
      issues: write         # required to create issues
      pull-requests: write  # required to create pull requests
    steps:
      - uses: actions/checkout@v4
      - name: Update Lean project
        uses: oliver-butterley/lean-update-action@v1-alpha
        with:
          on_update_succeeds: pr
          on_update_fails: issue
